---
- hosts: docker
  gather_facts: false
  remote_user: root
  tasks:

  
  - name: Building the my docker images
    docker_image:
      source: build
      name: nginx_image:latest
      build:
        path: ~/project
      state: present
  
  - name: Creating the container and start
    docker_container:
      name: nginx_container
      image: nginx_image:latest
       

 
