---
- hosts: docker
  gather_facts: false
  remote_user: root
  tasks:

  
  - name: Building the my docker images
    docker_image:
      source: build
      name: nginx_image:v1
      build:
        path: ~/project
      state: present
  
  - name: Creating the container and start
    docker_container:
      name: nginx_container
      image: nginx_image:v1
      ports:
        - "8183:80"
      state: started    

 
